# Generated by Django 5.0.6 on 2025-09-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_recurringtasktemplate_subtask_taskactivitylog_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='calendar_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
