# Generated by Django 5.0.6 on 2025-08-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Credit/Debit Card'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('paypal', 'PayPal'), ('other', 'Other')], max_length=20),
        ),
    ]
