# Generated by Django 5.2.4 on 2025-08-19 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_add_is_shared_field'),
        ('lists', '0002_templateitem'),
    ]

    operations = [
    ]
