# Generated by Django 5.2.4 on 2025-08-12 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_list_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
