# Generated by Django 5.2.4 on 2025-08-12 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0003_list_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='price',
        ),
        migrations.AddField(
            model_name='listitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
