# Generated by Django 5.0.6 on 2025-08-28 06:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_add_budget_field'),
        ('lists', '0003_merge_0002_add_is_shared_field_0002_templateitem'),
    ]

    operations = [
    ]
