# Generated by Django 5.2.4 on 2025-08-15 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_remove_list_price_listitem_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ListActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('created', 'Created'), ('updated', 'Updated'), ('item_added', 'Item Added'), ('item_completed', 'Item Completed'), ('item_removed', 'Item Removed'), ('shared', 'Shared'), ('archived', 'Archived')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ListAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField()),
                ('total_lists', models.IntegerField(default=0)),
                ('completed_lists', models.IntegerField(default=0)),
                ('total_items', models.IntegerField(default=0)),
                ('completed_items', models.IntegerField(default=0)),
                ('average_completion_time', models.DurationField(blank=True, null=True)),
                ('most_used_category', models.CharField(blank=True, max_length=50, null=True)),
                ('productivity_score', models.FloatField(default=0.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-month'],
            },
        ),
        migrations.CreateModel(
            name='ListCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('icon', models.CharField(default='list', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_level', models.CharField(choices=[('view', 'View Only'), ('edit', 'Edit Items'), ('admin', 'Full Access')], default='view', max_length=10)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ListTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(default='general', max_length=50)),
                ('is_public', models.BooleanField(default=False)),
                ('use_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='list',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='listitem',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AddField(
            model_name='list',
            name='actual_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='ai_suggestions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='list',
            name='auto_sort',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='list',
            name='completion_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='list',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='estimated_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='list',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='list',
            name='is_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='list',
            name='list_type',
            field=models.CharField(choices=[('checklist', 'Checklist'), ('shopping', 'Shopping List'), ('todo', 'To-Do List'), ('inventory', 'Inventory'), ('wishlist', 'Wishlist'), ('recipe', 'Recipe'), ('packing', 'Packing List'), ('other', 'Other')], default='checklist', max_length=20),
        ),
        migrations.AddField(
            model_name='list',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='list',
            name='sort_by',
            field=models.CharField(choices=[('name', 'Name'), ('priority', 'Priority'), ('created', 'Created Date'), ('price', 'Price'), ('quantity', 'Quantity')], default='created', max_length=20),
        ),
        migrations.AddField(
            model_name='listitem',
            name='ai_suggestions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='listitem',
            name='auto_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listitem',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='listitem',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='listitem',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listitem',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listitem',
            name='estimated_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='listitem',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listitem',
            name='is_recurring',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='listitem',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listitem',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listitem',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='listitem',
            name='recurring_frequency',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listitem',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='listitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='listitem',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='listitem',
            index=models.Index(fields=['list', 'is_completed'], name='lists_listi_list_id_81c6b5_idx'),
        ),
        migrations.AddIndex(
            model_name='listitem',
            index=models.Index(fields=['list', 'priority'], name='lists_listi_list_id_187cfd_idx'),
        ),
        migrations.AddField(
            model_name='listactivity',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='lists.list'),
        ),
        migrations.AddField(
            model_name='listactivity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listanalytics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listcategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='list',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lists.listcategory'),
        ),
        migrations.AddField(
            model_name='listshare',
            name='list',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lists.list'),
        ),
        migrations.AddField(
            model_name='listshare',
            name='shared_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_lists_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listshare',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='list',
            name='shared_with',
            field=models.ManyToManyField(related_name='shared_lists', through='lists.ListShare', through_fields=('list', 'user'), to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='listtemplate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='list',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lists.listtemplate'),
        ),
        migrations.AddIndex(
            model_name='list',
            index=models.Index(fields=['user', 'list_type'], name='lists_list_user_id_742bbf_idx'),
        ),
        migrations.AddIndex(
            model_name='list',
            index=models.Index(fields=['user', 'is_archived'], name='lists_list_user_id_b40f8e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='listanalytics',
            unique_together={('user', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='listcategory',
            unique_together={('user', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='listshare',
            unique_together={('list', 'user')},
        ),
    ]
