# Generated by Django 5.2.4 on 2025-08-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_listactivity_listanalytics_listcategory_listshare_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listtemplate',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
