# Generated by Django 5.2.4 on 2025-08-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0006_listtemplate_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='listitem',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
